<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="N. V. Schenk">

<title>Module1: Hello, World!</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Module1_Hello_World_files/libs/clipboard/clipboard.min.js"></script>
<script src="Module1_Hello_World_files/libs/quarto-html/quarto.js"></script>
<script src="Module1_Hello_World_files/libs/quarto-html/popper.min.js"></script>
<script src="Module1_Hello_World_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Module1_Hello_World_files/libs/quarto-html/anchor.min.js"></script>
<link href="Module1_Hello_World_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Module1_Hello_World_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Module1_Hello_World_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Module1_Hello_World_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Module1_Hello_World_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Module1: Hello, World!</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>N. V. Schenk </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<p>This document describes Module 1 of the course “Introduction to R”, held in Summer 2023 for the <a href="www.biodiversity-exploratories.de">Biodiversity Exploratories</a>.</p>
<section id="learning-outcome" class="level1">
<h1>Learning outcome</h1>
<ul>
<li>getting familiar with R</li>
<li>hands on!</li>
<li>establish workflow for this course</li>
<li>experience your first moments of success with programming</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>In order to learn coding, you need to code</p>
</div>
</div>
<section id="content" class="level2">
<h2 class="anchored" data-anchor-id="content">Content</h2>
<p>this Module is splitted into TODO_number chapters. The chapters are intented to be worked on sequentially, but feel free to try working on them in any other order (please report back if recommendable).</p>
<p>TODO add table of content</p>
</section>
<section id="prerequisites" class="level2">
<h2 class="anchored" data-anchor-id="prerequisites">Prerequisites</h2>
<p>A prerequisite of this course is having R and RStudio installed. If you did not do so, please follow Chapter 1.2 in “Beckmann”.</p>
</section>
</section>
<section id="hello-rstudio" class="level1">
<h1>1.1 Hello, RStudio!</h1>
<p><strong>Aim of this Module</strong> : getting familiar with RStudio.</p>
<p><strong>Material</strong> : Beckerman, Ch 1.4 - 1.11 and R4DS, Ch TODO (…)</p>
<p>During this chapter, you will be working with this document, and with Beckerman, Ch 1. While working througn this chapter, try to develop the habit to actively code while reading. Every time you see a code, try it out in your console! This whole chapter is about experiencing R. The more things you try out, the more you will develop a feeling about programming, and the easier it get to learn new things.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Most of the time we have to understand before we can act. In programming, it is the other way around. We have to act first in order to understand.</p>
</div>
</div>
<p>One of the key insights about learning how to program is that you have to experience it in order to understand. This can sometimes be difficult, because we are usually trained to understand first and act second, not to act before understanding. However, many concepts of programming are hard to understand without having experienced them, but easy to understand after you have already applied them.</p>
<p>During this chapter, practice to establish an active way of reading, having RStudio and the console open, and applying the exercises. Additionally, try out new things! Most examples can be slightly modified by you. You will see examples of this as you go through this module.</p>
<section id="beckerman-1.4---1.5" class="level2">
<h2 class="anchored" data-anchor-id="beckerman-1.4---1.5">Beckerman 1.4 - 1.5</h2>
<p>Please work through “Beckerman” Ch 1.4 and 1.5, and solve the below exercises after.</p>
<p>Please note the below discussion point, where the “Beckerman” book is recommending something I do not agree with.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Discussion point Beckerman Ch 1.6.1
</div>
</div>
<div class="callout-body-container callout-body">
<p>When introducing scripts, the Beckerman book recommends starting each script with :</p>
<p><code>rm(list = ls())</code></p>
<p>The book argues that : “It’s always good to start a script with nothing accidentally left over in R from a previous session.” Which is very legitimate.</p>
<p>We will discuss the reasons that speak against this during the discussion of module 1.</p>
<p>As an additional exercise, feel free to already explore the opinions, e.g.&nbsp;in Chapter 2.5 of <a href="https://rstats.wtf/source-and-blank-slates.html">this book</a>, or Chapter 17.1.2 of <a href="https://bookdown.org/pdr_higgins/rmrwr/intermediate-steps-toward-reproducibility.html">that book</a>, which includes a famous meme about this topic.</p>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Exercise</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Solution</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<p>Please compute the solution to the following mathematical operations using your R console :</p>
<p><span class="math inline">\(1 + 2\)</span></p>
<p><span class="math inline">\(5 / 8\)</span></p>
<p><span class="math inline">\(1 + 3 / 4\)</span></p>
<p><span class="math inline">\((1 + 3) / 4\)</span></p>
<p><span class="math inline">\(1 == 1\)</span></p>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell" data-hash="Module1_Hello_World_cache/html/unnamed-chunk-2_e8dada3a736d3b931cc635d84be72be4">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">+</span> <span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="dv">5</span> <span class="sc">/</span> <span class="dv">8</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.625</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">+</span> <span class="dv">3</span> <span class="sc">/</span> <span class="dv">4</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.75</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>(<span class="dv">1</span> <span class="sc">+</span> <span class="dv">3</span>) <span class="sc">/</span> <span class="dv">4</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># please note, that if no brackets are given, the division is computed first, addition second.</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">==</span> <span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true" href="">Exercise</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false" href="">Solution</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<p>Use R to create the integers from 2 to 10, inclusive.</p>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div class="cell" data-hash="Module1_Hello_World_cache/html/unnamed-chunk-3_686214d2a92d4300ac46c7365f009254">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">:</span><span class="dv">10</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  2  3  4  5  6  7  8  9 10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">2</span>, <span class="at">to =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  2  3  4  5  6  7  8  9 10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">2</span>, <span class="at">to =</span> <span class="dv">10</span>, <span class="at">by =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  2  3  4  5  6  7  8  9 10</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true" href="">Exercise</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false" href="">Solution</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<p>Use R to create the integers from 100 to 200, inclusive. Save them in a variable called <code>vec1</code></p>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<p>There are (at least) tree solutions :</p>
<div class="cell" data-hash="Module1_Hello_World_cache/html/unnamed-chunk-4_c98e8302ddf9f2fea8e754c5fee66701">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>vec1 <span class="ot">&lt;-</span> <span class="dv">100</span><span class="sc">:</span><span class="dv">200</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>vec1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 [19] 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 [37] 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 [55] 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 [73] 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 [91] 190 191 192 193 194 195 196 197 198 199 200</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>vec1 <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">100</span>, <span class="at">to =</span> <span class="dv">200</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>vec1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 [19] 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 [37] 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 [55] 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 [73] 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 [91] 190 191 192 193 194 195 196 197 198 199 200</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>vec1 <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">100</span>, <span class="at">to =</span> <span class="dv">200</span>, <span class="at">by =</span> <span class="dv">1</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>vec1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 [19] 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 [37] 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 [55] 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 [73] 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 [91] 190 191 192 193 194 195 196 197 198 199 200</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true" href="">Exercise</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false" href="">Solution</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<p>Use R to create the numbers from 100 to 200, using steps of 0.5. In other words, create the numbers <span class="math inline">\(100, 100.5, 101, 101.5, ... ,199.5, 200\)</span>.</p>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<div class="cell" data-hash="Module1_Hello_World_cache/html/unnamed-chunk-5_d5169d2ce9ac88fd374c972fad5cdc7a">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">100</span>, <span class="at">to =</span> <span class="dv">200</span>, <span class="at">by =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] 100.0 100.5 101.0 101.5 102.0 102.5 103.0 103.5 104.0 104.5 105.0 105.5
 [13] 106.0 106.5 107.0 107.5 108.0 108.5 109.0 109.5 110.0 110.5 111.0 111.5
 [25] 112.0 112.5 113.0 113.5 114.0 114.5 115.0 115.5 116.0 116.5 117.0 117.5
 [37] 118.0 118.5 119.0 119.5 120.0 120.5 121.0 121.5 122.0 122.5 123.0 123.5
 [49] 124.0 124.5 125.0 125.5 126.0 126.5 127.0 127.5 128.0 128.5 129.0 129.5
 [61] 130.0 130.5 131.0 131.5 132.0 132.5 133.0 133.5 134.0 134.5 135.0 135.5
 [73] 136.0 136.5 137.0 137.5 138.0 138.5 139.0 139.5 140.0 140.5 141.0 141.5
 [85] 142.0 142.5 143.0 143.5 144.0 144.5 145.0 145.5 146.0 146.5 147.0 147.5
 [97] 148.0 148.5 149.0 149.5 150.0 150.5 151.0 151.5 152.0 152.5 153.0 153.5
[109] 154.0 154.5 155.0 155.5 156.0 156.5 157.0 157.5 158.0 158.5 159.0 159.5
[121] 160.0 160.5 161.0 161.5 162.0 162.5 163.0 163.5 164.0 164.5 165.0 165.5
[133] 166.0 166.5 167.0 167.5 168.0 168.5 169.0 169.5 170.0 170.5 171.0 171.5
[145] 172.0 172.5 173.0 173.5 174.0 174.5 175.0 175.5 176.0 176.5 177.0 177.5
[157] 178.0 178.5 179.0 179.5 180.0 180.5 181.0 181.5 182.0 182.5 183.0 183.5
[169] 184.0 184.5 185.0 185.5 186.0 186.5 187.0 187.5 188.0 188.5 189.0 189.5
[181] 190.0 190.5 191.0 191.5 192.0 192.5 193.0 193.5 194.0 194.5 195.0 195.5
[193] 196.0 196.5 197.0 197.5 198.0 198.5 199.0 199.5 200.0</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-5-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-1" role="tab" aria-controls="tabset-5-1" aria-selected="true" href="">Exercise</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-2" role="tab" aria-controls="tabset-5-2" aria-selected="false" href="">Solution</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-5-1-tab">
<p>Please give us the sequence of numbers that begins at 73, ends at 156, and has a 0.23 unit difference between the numbers.</p>
<p>Did you notice something special?</p>
</div>
<div id="tabset-5-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-2-tab">
<div class="cell" data-hash="Module1_Hello_World_cache/html/unnamed-chunk-6_529f356d5537f761ba9829b66f415bac">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">73</span>, <span class="at">to =</span> <span class="dv">156</span>, <span class="at">by =</span> <span class="fl">0.23</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1]  73.00  73.23  73.46  73.69  73.92  74.15  74.38  74.61  74.84  75.07
 [11]  75.30  75.53  75.76  75.99  76.22  76.45  76.68  76.91  77.14  77.37
 [21]  77.60  77.83  78.06  78.29  78.52  78.75  78.98  79.21  79.44  79.67
 [31]  79.90  80.13  80.36  80.59  80.82  81.05  81.28  81.51  81.74  81.97
 [41]  82.20  82.43  82.66  82.89  83.12  83.35  83.58  83.81  84.04  84.27
 [51]  84.50  84.73  84.96  85.19  85.42  85.65  85.88  86.11  86.34  86.57
 [61]  86.80  87.03  87.26  87.49  87.72  87.95  88.18  88.41  88.64  88.87
 [71]  89.10  89.33  89.56  89.79  90.02  90.25  90.48  90.71  90.94  91.17
 [81]  91.40  91.63  91.86  92.09  92.32  92.55  92.78  93.01  93.24  93.47
 [91]  93.70  93.93  94.16  94.39  94.62  94.85  95.08  95.31  95.54  95.77
[101]  96.00  96.23  96.46  96.69  96.92  97.15  97.38  97.61  97.84  98.07
[111]  98.30  98.53  98.76  98.99  99.22  99.45  99.68  99.91 100.14 100.37
[121] 100.60 100.83 101.06 101.29 101.52 101.75 101.98 102.21 102.44 102.67
[131] 102.90 103.13 103.36 103.59 103.82 104.05 104.28 104.51 104.74 104.97
[141] 105.20 105.43 105.66 105.89 106.12 106.35 106.58 106.81 107.04 107.27
[151] 107.50 107.73 107.96 108.19 108.42 108.65 108.88 109.11 109.34 109.57
[161] 109.80 110.03 110.26 110.49 110.72 110.95 111.18 111.41 111.64 111.87
[171] 112.10 112.33 112.56 112.79 113.02 113.25 113.48 113.71 113.94 114.17
[181] 114.40 114.63 114.86 115.09 115.32 115.55 115.78 116.01 116.24 116.47
[191] 116.70 116.93 117.16 117.39 117.62 117.85 118.08 118.31 118.54 118.77
[201] 119.00 119.23 119.46 119.69 119.92 120.15 120.38 120.61 120.84 121.07
[211] 121.30 121.53 121.76 121.99 122.22 122.45 122.68 122.91 123.14 123.37
[221] 123.60 123.83 124.06 124.29 124.52 124.75 124.98 125.21 125.44 125.67
[231] 125.90 126.13 126.36 126.59 126.82 127.05 127.28 127.51 127.74 127.97
[241] 128.20 128.43 128.66 128.89 129.12 129.35 129.58 129.81 130.04 130.27
[251] 130.50 130.73 130.96 131.19 131.42 131.65 131.88 132.11 132.34 132.57
[261] 132.80 133.03 133.26 133.49 133.72 133.95 134.18 134.41 134.64 134.87
[271] 135.10 135.33 135.56 135.79 136.02 136.25 136.48 136.71 136.94 137.17
[281] 137.40 137.63 137.86 138.09 138.32 138.55 138.78 139.01 139.24 139.47
[291] 139.70 139.93 140.16 140.39 140.62 140.85 141.08 141.31 141.54 141.77
[301] 142.00 142.23 142.46 142.69 142.92 143.15 143.38 143.61 143.84 144.07
[311] 144.30 144.53 144.76 144.99 145.22 145.45 145.68 145.91 146.14 146.37
[321] 146.60 146.83 147.06 147.29 147.52 147.75 147.98 148.21 148.44 148.67
[331] 148.90 149.13 149.36 149.59 149.82 150.05 150.28 150.51 150.74 150.97
[341] 151.20 151.43 151.66 151.89 152.12 152.35 152.58 152.81 153.04 153.27
[351] 153.50 153.73 153.96 154.19 154.42 154.65 154.88 155.11 155.34 155.57
[361] 155.80</code></pre>
</div>
</div>
<p>Please notice that in this case, the vector (the sequence of numbers) does not end with 156, but with 155.8. This is because the interval of numbers is not divisible through the step size of 0.23 without rest. The <code>seq()</code> function thus starts at the number given by the parameter <code>from</code>, and ends at the closest number equal or smaller than the number given by the <code>to</code> parameter.</p>
</div>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-6-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-1" role="tab" aria-controls="tabset-6-1" aria-selected="true" href="">Exercise</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-2" role="tab" aria-controls="tabset-6-2" aria-selected="false" href="">Solution</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-6-1-tab">
<p>Create two sequences of numbers : The first is a sequence of numbers from 0 to 10, with steps of 1. Save this sequence in a variable called <code>a</code>. The second sequence is a sequence of numbers from 0 to 1, with steps of 0.1. Save this sequence in a variable called <code>b</code>.</p>
<p>Add the sequences a and b.</p>
</div>
<div id="tabset-6-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-2-tab">
<div class="cell" data-hash="Module1_Hello_World_cache/html/unnamed-chunk-7_d0cdfa72e07dd994995cff41f96ae3f1">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">10</span>, <span class="at">by =</span> <span class="dv">1</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.1</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>a <span class="sc">+</span> b</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  0.0  1.1  2.2  3.3  4.4  5.5  6.6  7.7  8.8  9.9 11.0</code></pre>
</div>
</div>
<p>Two vectors of the same length can be added easily.</p>
<p>Additional : You can check the length of a vector in R by using :</p>
<div class="cell" data-hash="Module1_Hello_World_cache/html/unnamed-chunk-8_c236390a71e83856087b4e5fc8fa19fa">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-7-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-1" role="tab" aria-controls="tabset-7-1" aria-selected="true" href="">Exercise</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-7-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-2" role="tab" aria-controls="tabset-7-2" aria-selected="false" href="">Solution</a></li></ul>
<div class="tab-content">
<div id="tabset-7-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-7-1-tab">
<p>Create two sequences of numbers : The first is a sequence of numbers from 0 to 10, with steps of 1. Save this sequence in a variable called <code>a</code>. The second sequence is a sequence of numbers from 0 to 1, with steps of 0.1. Save this sequence in a variable called <code>b</code>.</p>
<p>Add the sequences a and b.</p>
<p>What do you observe? Can you explain why?</p>
</div>
<div id="tabset-7-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-7-2-tab">
<div class="cell" data-hash="Module1_Hello_World_cache/html/unnamed-chunk-9_c014526f0c8f8f5f51f83d013426b498">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">10</span>, <span class="at">by =</span> <span class="dv">1</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="fl">0.1</span>, <span class="at">to =</span> <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.1</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>a <span class="sc">+</span> b</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in a + b: longer object length is not a multiple of shorter object
length</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  0.1  1.2  2.3  3.4  4.5  5.6  6.7  7.8  8.9 10.0 10.1</code></pre>
</div>
</div>
<p>Besides the solution of the addition, you get a so-called warning message. R tells you, that something might have gotten wrong, and that you should double-check if the solution is correct.</p>
<div class="cell" data-hash="Module1_Hello_World_cache/html/unnamed-chunk-10_fff19869075bf76c4ce417dd49959c41">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10</code></pre>
</div>
</div>
<p>Here, vector a is 11 elements long (or in other words, sequence a has 11 numbers). Vector b is only 10 elements long, and thus 1 element shorter. When we add vector a to vector b, the first element of a is added to the first element of b, the second element of a is added to the second element of b and so on.</p>
<p><code>0 + 0.0  1 + 0.1 ... 9 + 0.9 ...</code></p>
<p>However, after we added the tenth element of a to the tenth element of b or in other words, added 9 + 0.9, vector b has no other elments. Therefore, R is <strong>extending vector b with its first element</strong>. It is adding the last element of a, which is 10, to the <strong>first</strong> element of b. R is re-using, or <strong>recycling</strong> the elements of vector b in order to extend b to the length of a.</p>
<p><code>10 + 0</code></p>
<p>See the next exercise about the same topic to deepen your understanding.</p>
</div>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-8-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-1" role="tab" aria-controls="tabset-8-1" aria-selected="true" href="">Exercise</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-8-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-2" role="tab" aria-controls="tabset-8-2" aria-selected="false" href="">Solution</a></li></ul>
<div class="tab-content">
<div id="tabset-8-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-8-1-tab">
<p>Create two sequences of numbers : The first is a sequence of numbers from 1 to 5, with steps of 1. Save this sequence in a variable called <code>a</code>. The second sequence is a sequence of numbers from 0.1 to 0.3, with steps of 0.1. Save this sequence in a variable called <code>b</code>.</p>
<p>Add the sequences a and b.</p>
<p>What do you observe? Can you explain why?</p>
</div>
<div id="tabset-8-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-8-2-tab">
<div class="cell" data-hash="Module1_Hello_World_cache/html/unnamed-chunk-11_cf2a171fa58bc5e6a963776cb6035ce0">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">1</span>, <span class="at">to =</span> <span class="dv">5</span>, <span class="at">by =</span> <span class="dv">1</span>)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="fl">0.1</span>, <span class="at">to =</span> <span class="fl">0.3</span>, <span class="at">by =</span> <span class="fl">0.1</span>)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>a <span class="sc">+</span> b</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in a + b: longer object length is not a multiple of shorter object
length</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.1 2.2 3.3 4.1 5.2</code></pre>
</div>
</div>
<p>Again, you get the warning message telling you, that one of the vectors is shorter than the other.</p>
<p>Because a is longer than <code>b</code>, R is recycling the elements of b to extend it to the length of a. a is 5 elements long. b is 3 elements long. R extends the vector b to the length 5, by adding the first two elements at the end :</p>
<p><code>0.1 0.2 0.3 0.1 0.2</code></p>
<p>and adding this to the vector a. We end up with the vector :</p>
<p><code>1.1 2.2 3.3 4.1 5.2</code></p>
<p><code>1+0.1 2+0.2 3+0.3 4+0.1 5+0.2</code></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Checkpoint
</div>
</div>
<div class="callout-body-container callout-body">
<p>Please invent and write down 1-2 exercises including solutions about the past section. You can slightly modify one of the above or the book exercises, or think about a new one.</p>
<p>TODO : where to collect the exercises? In which module will we work on them? Submit as R files to me</p>
<p>I will collect the exercises of everyone during the course, and provide them to you for the last module.</p>
</div>
</div>
</section>
<section id="beckerman-1.6---1.9" class="level2">
<h2 class="anchored" data-anchor-id="beckerman-1.6---1.9">Beckerman 1.6 - 1.9</h2>
<p>In the previous section, you were given many additional exercises. The aim of this was to show you some possibilities to just slightly modify the examples from the book, in order to create new exercises. When reading the next chapters, please continue trying out slightly modifying the examples from the book yourself, in order to get more practice.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Discussion point
</div>
</div>
<div class="callout-body-container callout-body">
<p>During the discussion of Module 1, we will discuss about this practice of applying all exercises from the book and slightly modifying them - in order to maximise the practice. Please record your experiences and report them in class, during the discussion of Module 1.</p>
<p>Is this approach easy/difficult for you? Do you need anything to make it easier? Do you have some helpful advice/ insight for the class?</p>
<p>TODO record this discussion point.</p>
</div>
</div>
<p>Please work through “Beckerman” Ch 1.6 - 1.9 (including the package installation in 1.8), and solve the below exercises after.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-9-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-9-1" role="tab" aria-controls="tabset-9-1" aria-selected="true" href="">Exercise</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-9-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-9-2" role="tab" aria-controls="tabset-9-2" aria-selected="false" href="">Solution</a></li></ul>
<div class="tab-content">
<div id="tabset-9-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-9-1-tab">
<p>Create a new script called “my_test_script1.R”. Follow the instructions from the Beckerman book about the first few lines, except the part about adding the line <code>rm(list = ls())</code> (although they really seem to recommend it).</p>
<p>In the script, create a vector of numbers between 12 and 24, with a step size of 1. Give the vector a name of your choice, and print it to the console (write the name again below, so when running the given line, the vector is shown in the console panel).</p>
</div>
<div id="tabset-9-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-9-2-tab">
<p>Your script could look e.g.&nbsp;like this</p>
<pre><code># Amazing R User (your name)
# 18 August, 2023
# This is my first R script. I create a vector and call it.
# No R packages are required.

my_first_vector &lt;- seq(from = 12, to = 24, by = 1)
my_first_vector
</code></pre>
</div>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-10-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-10-1" role="tab" aria-controls="tabset-10-1" aria-selected="true" href="">Exercise</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-10-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-10-2" role="tab" aria-controls="tabset-10-2" aria-selected="false" href="">Hint</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-10-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-10-3" role="tab" aria-controls="tabset-10-3" aria-selected="false" href="">Solution</a></li></ul>
<div class="tab-content">
<div id="tabset-10-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-10-1-tab">
<p>Create a new script called “my_test_script2.R”. Follow the instructions from the Beckerman book about the first few lines, except the part about adding the line <code>rm(list = ls())</code> (although they really seem to recommend it).</p>
<p>Create the a vector from 1 to 240 with stepsize 1, and call it <code>a</code>. Create a second vector <code>b</code>, which is the square of vector <code>a</code>.</p>
<p>Create a plot of vector a and b, by adding the following code : <code>plot(a, b)</code></p>
</div>
<div id="tabset-10-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-10-2-tab">
<p>You can calculate the square of a vector as following :</p>
<div class="cell" data-hash="Module1_Hello_World_cache/html/unnamed-chunk-12_3756f31ef7dcc26afb6935d31cef76c4">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># creating vector a</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">12</span>, <span class="at">to =</span> <span class="dv">24</span>, <span class="at">by =</span> <span class="dv">1</span>)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Option one: using **</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>a<span class="sc">**</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 144 169 196 225 256 289 324 361 400 441 484 529 576</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Option two : using ^</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>a<span class="sc">^</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 144 169 196 225 256 289 324 361 400 441 484 529 576</code></pre>
</div>
</div>
</div>
<div id="tabset-10-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-10-3-tab">
<p>Your script could look e.g.&nbsp;like this</p>
<div class="cell" data-hash="Module1_Hello_World_cache/html/unnamed-chunk-13_5fd1b11569bb6431d94906be4afdef4a">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Amazing R User (your name)</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 18 August, 2023</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating vector and plotting them.</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="co"># creating vector a</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">1</span>, <span class="at">to =</span> <span class="dv">240</span>, <span class="at">by =</span> <span class="dv">1</span>)</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating vector b, using ** (note : alternatively, you can use the ** operation)</span></span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> a<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a><span class="co"># plotting a and b</span></span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(a, b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Module1_Hello_World_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Congratulations, you just created your first plot!</p>
</div>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-11-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-11-1" role="tab" aria-controls="tabset-11-1" aria-selected="true" href="">Exercise</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-11-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-11-2" role="tab" aria-controls="tabset-11-2" aria-selected="false" href="">Solution</a></li></ul>
<div class="tab-content">
<div id="tabset-11-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-11-1-tab">
<p>Create a new script called “my_test_script3.R”. Follow the instructions from the Beckerman book about the first few lines, except the part about adding the line <code>rm(list = ls())</code> (although they really seem to recommend it).</p>
<p>Load the package <code>ggplot2</code>. This is a package used for plotting.</p>
<p>Create the a vector from 1 to 240 with stepsize 1, and call it <code>a</code>. Create a second vector <code>b</code>, which is the square of vector <code>a</code>.</p>
<p>Create a plot of vector a and b, by using a function from the package <code>ggplot2</code>, adding the following code (don’t worry if you don’t understand the details, this will be covered later):</p>
<pre><code>qplot(x = a, y = b)
ggplot(data.frame(a, b), aes(x = a, y = b)) + 
  geom_line()</code></pre>
</div>
<div id="tabset-11-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-11-2-tab">
<div class="cell" data-hash="Module1_Hello_World_cache/html/unnamed-chunk-14_f4020e2eb5c00f4625ac0db4b4ae841c">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Amazing R User (your name)</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 18 August, 2023</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating vector and plotting them with ggplot2.</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a><span class="co"># creating vector a</span></span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">1</span>, <span class="at">to =</span> <span class="dv">240</span>, <span class="at">by =</span> <span class="dv">1</span>)</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating vector b, using ** (note : alternatively, you can use the ** operation)</span></span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> a<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a><span class="co"># plotting a and b</span></span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(a, b), <span class="fu">aes</span>(<span class="at">x =</span> a, <span class="at">y =</span> b)) <span class="sc">+</span> </span>
<span id="cb50-15"><a href="#cb50-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Module1_Hello_World_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Take-home : You are already able to create a plot in R!</p>
<p>Take-home 2 : R packages : Much of the often used code in R comes in software packages, which are added “on top” of the basic R. We can load a package with the <code>library()</code> function. A software package, like e.g.&nbsp;<code>ggplot2</code> provides more functions. In the case of <code>ggplot2</code>, those are functions for creating nice looking plots.</p>
</div>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-12-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-12-1" role="tab" aria-controls="tabset-12-1" aria-selected="true" href="">Exercise</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-12-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-12-2" role="tab" aria-controls="tabset-12-2" aria-selected="false" href="">Solution</a></li></ul>
<div class="tab-content">
<div id="tabset-12-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-12-1-tab">
<p>In your script “my_test_script3.R”, add the following new command : <code>fortune()</code>, and see what happens. Can you explain why?</p>
</div>
<div id="tabset-12-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-12-2-tab">
<p>You get an error message, saying : <code>Error in fortunes() : could not find function "fortunes"</code></p>
<p>If we call a function (try to use a function) from a package which is not installed, we get an error message.</p>
</div>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-13-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-13-1" role="tab" aria-controls="tabset-13-1" aria-selected="true" href="">Exercise</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-13-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-13-2" role="tab" aria-controls="tabset-13-2" aria-selected="false" href="">Solution</a></li></ul>
<div class="tab-content">
<div id="tabset-13-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-13-1-tab">
<p>The function <code>fortunes()</code> is from a package called <code>fortunes</code>. Install and load the package <code>fortunes</code> and call the function <code>fortune()</code> again.</p>
<p>What happens?</p>
</div>
<div id="tabset-13-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-13-2-tab">
<p>Install the <code>fortunes</code> package using the function : <code>install.packages("fortunes")</code></p>
<p>Add the below code to your script :</p>
<div class="cell" data-hash="Module1_Hello_World_cache/html/unnamed-chunk-15_38097ad70d37f103dc685aac7d4ec16d">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fortunes)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">fortune</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
There's probably some examples, but there are some examples of people using
  solve(t(X) %*% W %*% X) %*% W %*% Y
to compute regression coefficients, too.
   -- Thomas Lumley (discussing usefulness of evaluation order in lapply)
      R-help (March 2006)</code></pre>
</div>
</div>
<p>This package only consists of a single function, giving you random fortunes about R. It exists just for fun.</p>
<p>If you would like to try out some more “just for fun” packages, see e.g.&nbsp;<a href="https://towardsdatascience.com/make-learning-r-fun-with-these-5-packages-3c3f6ca82c96">here</a></p>
</div>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-14-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-14-1" role="tab" aria-controls="tabset-14-1" aria-selected="true" href="">Exercise</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-14-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-14-2" role="tab" aria-controls="tabset-14-2" aria-selected="false" href="">Solution</a></li></ul>
<div class="tab-content">
<div id="tabset-14-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-14-1-tab">
<p>What are the advantages of using a scripted language (like R) over using a point-and-click language (like Excel)? Name 3 advantages.</p>
<p>Note that you don’t have to stick to the points mentioned in the book, but add points from other sources or from your experience.</p>
</div>
<div id="tabset-14-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-14-2-tab">
<p>You find some of these points in Section 1.7.</p>
<ul>
<li>The analysis is fully reproducible with a script (i.e.&nbsp;someone else can perform exactly the same steps as you have done)</li>
<li>Scripts are easy to share. An advantage of using R is that many researchers are using R as well, which makes it easier to understand each other’s work.</li>
<li>R is a free software (contrary to many, but not all point-and-click softwares, e.g.&nbsp;LibreOffice calc which works similar to Excel is freely available)</li>
<li>R allows annotating steps of the analysis, e.g.&nbsp;decisions taken during data cleaning or analysis.</li>
<li>R can be used for (many) full analyses from data cleaning to visualisation (not switching from one platform to another)
<ul>
<li>Additionally, it is possible to combine multiple programming languages like e.g.&nbsp;Julia, Python, bash, … or multiple kind of analyses (GIS, phylogenetics, multivariate, Bayesian, …) in one script using Rmarkdown or Quarto (which are included in RStudio) and multiple R packages.</li>
</ul></li>
<li>Automation : Scripts allow running the same steps over and over again upon small changes. Rerunning code is one click.</li>
</ul>
<p>Sources :</p>
<ul>
<li>Beckerman Chapter 1.7.</li>
<li>Chapter 5.3.2 of <a href="https://www.ecologi.st/BIO3019S_Ecoforecasting/reproducibility.html#reproducible-scientific-workflows">“A Minimal Introduction to Ecological Forecasting” Jasper Slingsby, 2023-07-31</a></li>
</ul>
</div>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-15-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-15-1" role="tab" aria-controls="tabset-15-1" aria-selected="true" href="">Exercise</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-15-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-15-2" role="tab" aria-controls="tabset-15-2" aria-selected="false" href="">Solution</a></li></ul>
<div class="tab-content">
<div id="tabset-15-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-15-1-tab">
<p>Find and download a cheatsheet for so-called “basic R” and identify the commands you already learned.</p>
<p>If you want, you can use <a href="https://iqss.github.io/dss-workshops/R/Rintro/base-r-cheat-sheet.pdf">this</a> one.</p>
<p>Note that if you wish to create your own cheatsheet, there are templates available, e.g.&nbsp;<a href="https://github.com/rstudio/cheatsheets/tree/main/powerpoints">here</a>. You can download a pretty cheat sheet and modify it yourself.</p>
</div>
<div id="tabset-15-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-15-2-tab">
<p>On the <a href="https://iqss.github.io/dss-workshops/R/Rintro/base-r-cheat-sheet.pdf">Example Cheat Sheet</a>, we e.g.&nbsp;already saw the following commands : <code>?</code>, <code>help</code>, <code>install.packages</code>, <code>seq</code>, <code>length</code> and probably some more.</p>
</div>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-16-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-16-1" role="tab" aria-controls="tabset-16-1" aria-selected="true" href="">Exercise</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-16-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-16-2" role="tab" aria-controls="tabset-16-2" aria-selected="false" href="">Solution</a></li></ul>
<div class="tab-content">
<div id="tabset-16-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-16-1-tab">
<p>Name 5 sources of help in R and RStudio.</p>
</div>
<div id="tabset-16-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-16-2-tab">
<p>from within R :</p>
<ul>
<li>the <code>help()</code> function (or, analogously the <code>?</code> function)</li>
</ul>
<div class="cell" data-hash="Module1_Hello_World_cache/html/unnamed-chunk-16_2df0e9c224c45114217a92c222da7cd4">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">help</span>(mean)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>?mean</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><strong>Cheatsheets</strong> : within RStudio, click on Help &gt; Cheat Sheets and e.g.&nbsp;Browse Cheatsheets. On the “Contributed Cheatsheets” section, you find cheat sheets written by other R users.</li>
</ul>
<p>from the internet :</p>
<ul>
<li>Use your favourite search engine (e.g.&nbsp;Google)</li>
<li><a href="http://stackoverflow.com/tags/r/info">stackoverflow</a></li>
<li><a href="https://www.r-bloggers.com/">R bloggers</a></li>
<li><a href="rseek.org">RSeek</a></li>
<li>ChatGPT</li>
<li>watch YouTube videos</li>
</ul>
<p>from other humans:</p>
<ul>
<li>ask people from this course (e.g.&nbsp;via slack channel)</li>
<li>ask people around you (also the ones still learning R!)</li>
<li>ask yourself in a forum (e.g.&nbsp;Stackoverflow)</li>
<li>join coding clubs or seminars about R</li>
<li>ask me</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Checkpoint
</div>
</div>
<div class="callout-body-container callout-body">
<p>Please invent and write down 1-2 exercises including solutions about the past section. You can slightly modify one of the above or the book exercises, or think about a new one.</p>
<p>TODO : where to collect the exercises? In which module will we work on them? Submit as R files to me via email</p>
<p>I will collect the exercises of everyone during the course, and provide them to you for the last module.</p>
</div>
</div>
</section>
<section id="r4ds-1.4" class="level2">
<h2 class="anchored" data-anchor-id="r4ds-1.4">R4DS 1.4</h2>
<p>Please read and work through (the very short) Chapter 1.4. in R4DS. You will see some topics repeated.</p>
<p>Goals : Get familiar with the R4DS book and learn about the existence of the <code>tidyverse</code> group of packages.</p>
</section>
<section id="beckerman-1.10---1.11" class="level2">
<h2 class="anchored" data-anchor-id="beckerman-1.10---1.11">Beckerman 1.10 - 1.11</h2>
<p>Please work through “Beckerman” Ch 1.10 - 1.11, and solve the below exercises after. Please take enough time for the Exercise in 1.10.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-17-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-17-1" role="tab" aria-controls="tabset-17-1" aria-selected="true" href="">Exercise</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-17-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-17-2" role="tab" aria-controls="tabset-17-2" aria-selected="false" href="">Solution</a></li></ul>
<div class="tab-content">
<div id="tabset-17-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-17-1-tab">
<p>Does Beckerman recommend to save the workspace at quitting RStudio? Why (include your own opinion)?</p>
</div>
<div id="tabset-17-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-17-2-tab">
<p>No, this is not recommended. Not saving the workspace strongly encourages a reproducible workflow. If you are ready to reproduce everything done within a script without having to consider external resources (e.g.&nbsp;finding a variable <code>a</code> which is used, but never created), the script is reproducible.</p>
<p>Note : if you don’t know what a workspace is, please ask during the questions session. It is not a prerequisite for the below exercises.</p>
</div>
</div>
</div>
<p>If you have enough time, feel free to read Appendix 1b as well.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Checkpoint
</div>
</div>
<div class="callout-body-container callout-body">
<p>Please invent and write down 1-2 exercises including solutions about the past two sections. You can slightly modify one of the above or the book exercises, or think about a new one.</p>
<p>TODO : where to collect the exercises? In which module will we work on them? Submit as R files to me via email</p>
<p>I will collect the exercises of everyone during the course, and provide them to you for the last module.</p>
<p>–&gt; past 2 sections</p>
</div>
</div>
</section>
</section>
<section id="additional-play-and-practice-with-swirl" class="level1">
<h1>Additional : Play and practice with swirl</h1>
<p>If you have some time to practice, you can try out <code>swirl</code>, an R package which teaches you R.</p>
<p>Visit the page of <a href="https://swirlstats.com/students.html">swirl</a> and follow the installation procedure.</p>
<p>Just two small notes : - for now : data frames is just an R name for tables - Run head() on the cars data. means you have to type : <code>head(cars)</code> to the console - swirl is an interactive program. It will write you information to the console. You have to actively start <code>swirl()</code> and stop <code>bye()</code> it.</p>
<div class="cell" data-hash="Module1_Hello_World_cache/html/unnamed-chunk-17_a1bacd416346a60f1cee6cd507a6fa64">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"swirl"</span>)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(swirl)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="fu">install_course</span>(<span class="st">"R Programming E"</span>)</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a><span class="co"># swirl()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once you are ready to start using the package, type <code>swirl()</code>. Note that if you want to quit swirl, you have to press Esc or write <code>bye()</code> to the console.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>